#!/bin/sh

if [ -z "${SRCROOT}" ]; then
	echo "Error: this script must be run by Xcode"
	exit 1
fi

ZDOOM_EXEC_DIR=${CONFIGURATION_BUILD_DIR}/${EXECUTABLE_FOLDER_PATH}

if [ ! -e "${ZDOOM_EXEC_DIR}" ]; then
	mkdir -p "${ZDOOM_EXEC_DIR}"
fi

rsync -av "${SRCROOT}/thirdparty/FMOD/lib/libfmodex.dylib" "${ZDOOM_EXEC_DIR}"

ZDOOM_EXEC_FILE=${ZDOOM_EXEC_DIR}/${EXECUTABLE_NAME}

if [ -e "${ZDOOM_EXEC_FILE}" ]; then
	FMOD_LIB_NAME=libfmodex.dylib
	FMOD_NEED_FIX=`otool -L "${ZDOOM_EXEC_FILE}" | fgrep ./${FMOD_LIB_NAME}`

	if [ "${FMOD_NEED_FIX}" ]; then
		install_name_tool -change ./${FMOD_LIB_NAME} @executable_path/${FMOD_LIB_NAME} "${ZDOOM_EXEC_FILE}"
	fi
fi

ZIPDIR_EXE=${BUILD_DIR}/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/zipdir

if [ -e "${ZIPDIR_EXE}" ]; then
	"${ZIPDIR_EXE}" -ud "${ZDOOM_EXEC_DIR}/zdoom.pk3" "${SRCROOT}/wadsrc/static"
fi
