#!/bin/sh

if [ -z "${SRCROOT}" ]; then
	echo "Error: this script must be run by Xcode"
	exit 1
fi

echo "Generating sc_man_scanner.h..."

cd "${CONFIGURATION_BUILD_DIR}"
./re2c --no-generation-date -s -o sc_man_scanner.h "${SRCROOT}/src/sc_man_scanner.re"
