#!/bin/sh

if [ -z "${SRCROOT}" ]; then
	echo "Error: this script must be run by Xcode"
	exit 1
fi

echo "Generating xlat_parser.c and xlat_parser.h..."

rsync -av "${SRCROOT}/tools/lemon/lempar.c" "${CONFIGURATION_BUILD_DIR}"
rsync -av "${SRCROOT}/src/xlat/xlat_parser.y" "${CONFIGURATION_BUILD_DIR}"

cd "${CONFIGURATION_BUILD_DIR}"
./lemon xlat_parser.y
